name: Source Build
on:
  workflow_dispatch:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  source:
    name: source build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - uses: ros-tooling/setup-ros@0.7.1
        with:
          required-ros-distributions: rolling
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
      - uses: ros-tooling/action-ros-ci@0.3.5
        with:
          target-ros2-distro:  rolling
          # build all packages listed in the meta package
          ref: ${{ inputs.ref }}
          package-name:
            odri_bolt_description
            odri_bolt_bringup
          vcs-repo-file-url: |
            https://raw.githubusercontent.com/ros2/ros2/rolling/ros2.repos
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      - uses: actions/upload-artifact@v4.0.0
        with:
          name: colcon-logs-ubuntu-22.04
          path: ros_ws/log
